### ISSUE TITLE
『JIS X 8341-3』の公示年月日を知りたい

### ISSUE THREAD

**Issue by debiru** [waic/QandA#10]
- (Q1) 『JIS X 8341-3』の公示年月日を知りたいと思った場合、それが分かるウェブページはどこかあるでしょうか。
- (Q2) 「[JIS X 8341-3:2016 解説](https://waic.jp/docs/jis2016/understanding/201604/)」では「『JIS X 8341-3』改正の経緯」セクションに制定・改正の年月が書かれていますが、日が書かれていません。ここに日情報を追加いただくことは可能でしょうか。
- (Q3) もし Q2 の当該セクションに日情報を追加いただける場合、見出し「『JIS X 8341-3』改正の経緯」に id 属性を付与してページ内リンクを可能にしていただくことは可能でしょうか。

恐れ入りますが、ご確認いただけると幸いです。

**Comment by momdo** [comment]
@debiru 

> (Q1) 『JIS X 8341-3』の公示年月日を知りたいと思った場合、それが分かるウェブページはどこかあるでしょうか。

これについては、JSAのページの「履歴」で確認できるかと思います。

JIS X 8341-3:2016 高齢者・障害者等配慮設計指針―情報通信における機器，ソフトウェア及びサービス―第３部：ウェブコンテンツ | 日本規格協会 JSA Group Webdesk 
https://webdesk.jsa.or.jp/books/W11M0090/index/?bunsyo_id=JIS+X+8341-3%3A2016

JISの官報の掲載については、JISCにあるとおりです。

> 経済産業省が制定等を行うＪＩＳについては、特段の事情が無いかぎり、ＪＩＳの制定等の規格番号及び名称を毎月２０日（休日の場合は、直後の平日）の官報に掲載しています。また、不定期で２５日頃にも掲載もいたします。

日本産業標準調査会：産業標準化とJIS-JISの入手閲覧方法 
https://www.jisc.go.jp/jis-act/reading.html

Q2、Q3に関しては権限を持っていないため、私からは回答を差し控えさせていただきます。

上記で回答になっているでしょうか。

**Comment by debiru** [comment]
> 特段の事情が無いかぎり、ＪＩＳの制定等の規格番号及び名称を毎月２０日（休日の場合は、直後の平日）の官報に掲載しています。

そういう規則があったのですね。だから2004年は6月20日、2010年は8月20日で、2016年は祝日と振替休日の後の平日である3月22日となっているのですね。

> 上記で回答になっているでしょうか。

ありがとうございます。Wikipedia のようなウェブサイトに JIS X 8341-3 のことを記述する際に、公示日の出典がほしいと思っていたところでした。示していただいた JSA のウェブページで良さそうです。

(q2), (q3) は当該ページを出典として使う場合の話だったのですが、JSA ページがあるとのことでしたので対応いただかなくとも大丈夫そうです。ありがとうございました。
